# Generated by Django 6.0.5 on 2026-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
