# Generated by Django 6.0.5 on 2026-08-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransaction'),
        ('purchases', '0004_goodsreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='inventory.warehouselocation'),
        ),
    ]
