# Generated by Django 6.0.5 on 2026-08-02 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(default='Current', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Bank Account',
                'verbose_name_plural': 'Supplier Bank Accounts',
                'ordering': ['bank_name'],
            },
        ),
    ]
