# Generated by Django 6.0.5 on 2026-08-02 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplierbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('GST', 'GST Certificate'), ('PAN', 'PAN Card'), ('MSME', 'MSME Certificate'), ('AGREEMENT', 'Vendor Agreement'), ('BANK', 'Cancelled Cheque'), ('ISO', 'ISO Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('document_name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='suppliers/documents/')),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Document',
                'verbose_name_plural': 'Supplier Documents',
                'ordering': ['document_name'],
            },
        ),
    ]
