# Generated by Django 6.0.5 on 2026-08-04 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransaction'),
        ('sales', '0006_deliverynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.deliverynote')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='inventory.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='inventory.product')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='sales.salesorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
