# Generated by Django 6.0.5 on 2026-08-04 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_customerpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('return_number', models.CharField(max_length=30, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong Item'), ('EXPIRED', 'Expired'), ('CUSTOMER_REQUEST', 'Customer Request'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('APPROVED', 'Approved'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.customer')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.salesinvoice')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
    ]
