# Generated by Django 6.0.5 on 2026-08-04 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransaction'),
        ('sales', '0011_salesreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('SCRAP', 'Scrap')], default='GOOD', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_items', to='inventory.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='inventory.product')),
                ('sales_invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.salesinvoiceitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
