# Generated by Django 6.0.5 on 2026-07-31 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('location_type', models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH_OFFICE', 'Branch Office'), ('WAREHOUSE', 'Warehouse'), ('STORE', 'Retail Store'), ('FACTORY', 'Factory'), ('SERVICE_CENTER', 'Service Center')], max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.branch')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'code'), name='unique_location_code_per_branch')],
            },
        ),
    ]
